GET http://localhost:3000/api/profile/events/get-all
Content-Type: application/json

###

get http://127.0.0.1:3000/api/profile/get-all
Content-Type: application/json

###

POST http://127.0.0.1:3000/api/profile/create
Content-Type: application/json
{ 
"email": "vegeta@gmail.com", 
"password": 1234313125,
"username": "principe sayayin",
"profile_picture": "https://i.pinimg.com/736x/69/57/08/6957089f6bbcb0edf4108aac0febdc3f.jpg", 
"is_admin": true 
}

###

//sin URL de IMAGEN // 
POST http://127.0.0.1:3000/api/profile/add 
Content-Type: application/json


###

